### ISSUE TITLE
Model too large for size-limited license :sweat:

### ISSUE THREAD

**Issue by teng-gao** [raphael-group/MERLIN#3]
While trying to run the example I get:

```
Matplotlib is building the font cache; this may take a moment.
/Users/tgao/MERLIN/src/merlin.py:76: RuntimeWarning: invalid value encountered in scalar divide
  slope = np.dot(vaf1, vaf2) / np.dot(vaf1, vaf1)
Restricted license - for non-production use only - expires 2025-11-24
Set parameter TimeLimit to value 7200
Set parameter Threads to value 1
Set parameter Method to value 4
Gurobi Optimizer version 11.0.3 build v11.0.3rc0 (mac64[arm] - Darwin 23.6.0 23G93)

CPU model: Apple M2 Pro
Thread count: 10 physical cores, 10 logical processors, using up to 1 threads

Traceback (most recent call last):
  File "/Users/tgao/MERLIN/src/merlin.py", line 269, in <module>
    main()
  File "/Users/tgao/MERLIN/src/merlin.py", line 267, in main
    set_ILP_formuation(G_ancestry, cell2group, df_variant, df_total, args.out)
  File "/Users/tgao/MERLIN/src/merlin.py", line 230, in set_ILP_formuation
    model.optimize()
  File "src/gurobipy/model.pxi", line 893, in gurobipy.Model.optimize
gurobipy.GurobiError: Model too large for size-limited license; visit https://gurobi.com/unrestricted for more information
```
I don't have a license :sweat:

**Comment by teng-gao** [comment]
Oh, you can get a free license for research use here:

https://www.gurobi.com/academia/academic-program-and-licenses/
